kind: Cluster
apiVersion: kind.x-k8s.io/v1alpha4
nodes:
- role: control-plane

- role: worker
  labels:
    tier: frontend
  extraPortMappings:
  - containerPort: 30080
    hostPort: 80

- role: worker
  labels:
    tier: backend

- role: worker
  labels:
    tier: backend 

